### ISSUE TITLE
error: '_mpris_org_mpris_media_player2_player_method_info_p' undeclared here (not in a function)

### ISSUE THREAD

**Issue by region51** [gnome-mpv/gnome-mpv#101]
last commit Translate and validate appdata file https://github.com/gnome-mpv/gnome-mpv/commit/d9714cc80516d195c9bf1337118d37a33cbddbb8 broken 
```
mpris/mpris_gdbus.c:2443:4: error: '_mpris_org_mpris_media_player2_player_method_info_p' undeclared here (not in a function)
   &_mpris_org_mpris_media_player2_player_method_info_p
    ^
mpris/mpris_gdbus.c:2443:3: error: expected '}' at end of input
   &_mpris_org_mpris_media_player2_player_method_info_p
   ^
Makefile:744: recipe for target 'mpris/gnome_mpv-mpris_gdbus.o' failed
make[2]: *** [mpris/gnome_mpv-mpris_gdbus.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/builddir/build/BUILD/gnome-mpv-d9714cc80516d195c9bf1337118d37a33cbddbb8/src'
Makefile:340: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/builddir/build/BUILD/gnome-mpv-d9714cc80516d195c9bf1337118d37a33cbddbb8/src'
Makefile:385: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.t93Sir (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.t93Sir (%build)
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/gnome-mpv.spec 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 493, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/gnome-mpv.spec 
LEAVE do --> EXCEPTION RAISED

```

**Comment by region51** [comment]
2100b1a9d46bb0a6bc430a38ef5feede1d7ec327 OK

**Comment by region51** [comment]
2dd9086be1713f2697482db41d18969505451925 OK 

BuildRequires:  /usr/bin/appstream-util

aka

BuildRequires:  libappstream-glib

**Comment by region51** [comment]
Oops! In Fedora decision

BuildRequires:  pkgconfig(appstream-glib)
