### ISSUE TITLE
The latest git version crashed after clicking on the seekbar.

### ISSUE THREAD

**Issue by yjcoshc** [gnome-mpv/gnome-mpv#206]
Overview Description:
The latest git version crashed after clicking on the seekbar.

Error message:
[1]    27846 segmentation fault (core dumped)  G_MESSAGES_DEBUG=all gnome-mpv

Error message in dmesg: segfault at 7ffd284abff8 ip 00007f6848a1a8e5 sp 00007ffd284ac000 error 6 in libglib-2.0.so.0.4800.1[7f68489df000+110000]
I installed debuginfo rpms and ran it in gdb, the backtrace shows:
```
#0  0x00007ffff5e88999 in g_signal_emit_by_name (instance=0x555555a63400, detailed_signal=0x555555585e9f "seek") at gsignal.c:3462
#1  0x0000555555569a4c in seek_handler (widget=0x555555a63400 [GmpvSeekBar], scroll=1439084848, value=275.73795180722891, data=0x555555a63400) at gmpv_control_box.c:60
#2  0x00007ffff5e70214 in g_cclosure_marshal_VOID__DOUBLEv (closure=<optimized out>, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x555555c08f50) at gmarshal.c:1718
#3  0x00007ffff5e6da82 in _g_closure_invoke_va (closure=closure@entry=0x555555b9eea0, return_value=return_value@entry=0x0, instance=instance@entry=0x555555a63400, args=args@entry=0x7fffff7fe398, n_params=1, param_types=0x555555c08f50) at gclosure.c:867
#4  0x00007ffff5e8826d in g_signal_emit_valist (instance=instance@entry=0x555555a63400, signal_id=signal_id@entry=287, detail=detail@entry=0, var_args=var_args@entry=0x7fffff7fe398)
    at gsignal.c:3294
#5  0x00007ffff5e88e0b in g_signal_emit_by_name (instance=0x555555a63400, detailed_signal=0x555555585e9f "seek") at gsignal.c:3481
#6  0x0000555555569a4c in seek_handler (widget=0x555555a63400 [GmpvSeekBar], scroll=1439084848, value=275.73795180722891, data=0x555555a63400) at gmpv_control_box.c:60
#7  0x00007ffff5e70214 in g_cclosure_marshal_VOID__DOUBLEv (closure=<optimized out>, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x555555c08f50) at gmarshal.c:1718
#8  0x00007ffff5e6da82 in _g_closure_invoke_va (closure=closure@entry=0x555555b9eea0, return_value=return_value@entry=0x0, instance=instance@entry=0x555555a63400, args=args@entry=0x7fffff7fe798, n_params=1, param_types=0x555555c08f50) at gclosure.c:867
#9  0x00007ffff5e8826d in g_signal_emit_valist (instance=instance@entry=0x555555a63400, signal_id=signal_id@entry=287, detail=detail@entry=0, var_args=var_args@entry=0x7fffff7fe798)
    at gsignal.c:3294
#10 0x00007ffff5e88e0b in g_signal_emit_by_name (instance=0x555555a63400, detailed_signal=0x555555585e9f "seek") at gsignal.c:3481
#11 0x0000555555569a4c in seek_handler (widget=0x555555a63400 [GmpvSeekBar], scroll=1439084848, value=275.73795180722891, data=0x555555a63400) at gmpv_control_box.c:60
#12 0x00007ffff5e70214 in g_cclosure_marshal_VOID__DOUBLEv (closure=<optimized out>, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x555555c08f50) at gmarshal.c:1718
#13 0x00007ffff5e6da82 in _g_closure_invoke_va (closure=closure@entry=0x555555b9eea0, return_value=return_value@entry=0x0, instance=instance@entry=0x555555a63400, args=args@entry=0x7fffff7feb98, n_params=1, param_types=0x555555c08f50) at gclosure.c:867
#14 0x00007ffff5e8826d in g_signal_emit_valist (instance=instance@entry=0x555555a63400, signal_id=signal_id@entry=287, detail=detail@entry=0, var_args=var_args@entry=0x7fffff7feb98)
    at gsignal.c:3294
#15 0x00007ffff5e88e0b in g_signal_emit_by_name (instance=0x555555a63400, detailed_signal=0x555555585e9f "seek") at gsignal.c:3481
#16 0x0000555555569a4c in seek_handler (widget=0x555555a63400 [GmpvSeekBar], scroll=1439084848, value=275.73795180722891, data=0x555555a63400) at gmpv_control_box.c:60
#17 0x00007ffff5e70214 in g_cclosure_marshal_VOID__DOUBLEv (closure=<optimized out>, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x555555c08f50) at gmarshal.c:1718
#18 0x00007ffff5e6da82 in _g_closure_invoke_va (closure=closure@entry=0x555555b9eea0, return_value=return_value@entry=0x0, instance=instance@entry=0x555555a63400, args=args@entry=0x7fffff7fef98, n_params=1, param_types=0x555555c08f50) at gclosure.c:867
#19 0x00007ffff5e8826d in g_signal_emit_valist (instance=instance@entry=0x555555a63400, signal_id=signal_id@entry=287, detail=detail@entry=0, var_args=var_args@entry=0x7fffff7fef98)
    at gsignal.c:3294
---Type <return> to continue, or q <return> to quit---q

```
OS: opensuse tumbleweed
glib2 version is 2.48.1 (libglib-2_0-0-2.48.1-1.4.x86_64)
Steps to Reproduce:
1. Compile the latest git version of mpv and gnome-mpv.
2. Run gnome-mpv and open any mkv video.
3. Click on the seekbar.

Actual Results:
gnome-mpv crashes and exits.

Expected Results:
No crash.

Version:
38da9780f476dc4556ec0819c57784e854ac4905
Additional Information:

**Comment by region51** [comment]
I confirm
```
[maxim@localhost ~]$ G_MESSAGES_DEBUG=all gnome-mpv
** INFO: Single instance negotiation is disabled
(gnome-mpv:7586): Gtk-DEBUG: Connecting to session manager
** (gnome-mpv:7586): DEBUG: Applying default option --osd-level=1
** (gnome-mpv:7586): DEBUG: Applying default option --softvol=yes
** (gnome-mpv:7586): DEBUG: Applying default option --force-window=yes
** (gnome-mpv:7586): DEBUG: Applying default option --input-default-bindings=yes
** (gnome-mpv:7586): DEBUG: Applying default option --audio-client-name=gnome-mpv
** (gnome-mpv:7586): DEBUG: Applying default option --title=${media-title}
** (gnome-mpv:7586): DEBUG: Applying default option --autofit-larger=75%
** (gnome-mpv:7586): DEBUG: Applying default option --window-scale=1
** (gnome-mpv:7586): DEBUG: Applying default option --pause=no
** (gnome-mpv:7586): DEBUG: Applying default option --ytdl=yes
** (gnome-mpv:7586): DEBUG: Applying default option --osd-bar=no
** (gnome-mpv:7586): DEBUG: Applying default option --input-cursor=no
** (gnome-mpv:7586): DEBUG: Applying default option --cursor-autohide=no
** (gnome-mpv:7586): DEBUG: Applying default option --softvol-max=100
** (gnome-mpv:7586): DEBUG: Applying default option --config=yes
** (gnome-mpv:7586): DEBUG: Applying default option --screenshot-template=gnome-mpv-shot%n
** (gnome-mpv:7586): DEBUG: Applying default option --config-dir=/home/maxim/.config/gnome-mpv
** INFO: Loading config file: /home/maxim/.config/gnome-mpv/gnome-mpv.conf
** INFO: Loading input config file: /home/maxim/.config/gnome-mpv/input.conf
** (gnome-mpv:7586): DEBUG: Using temporary input config file: /tmp/.1Q2DKY
** INFO: Loaded input config file: /home/maxim/.config/gnome-mpv/input.conf
** (gnome-mpv:7586): DEBUG: Applying extra mpv options: --osc=no
** (gnome-mpv:7586): DEBUG: Applying option --osc=no
** (gnome-mpv:7586): DEBUG: Attaching mpv window to wid 0x160001a
** (gnome-mpv:7586): DEBUG: Setting volume to 100.000000
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "idle"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:7586): DEBUG: Adding property: CanSeek
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:7586): DEBUG: Adding property: CanSeek
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "speed"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "volume"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "playlist-count"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:7586): DEBUG: Adding property: CanSeek
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "fullscreen"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "pause"
** INFO: Loading file (append=FALSE, update=TRUE): <PLAYLIST_ITEMS>
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "track-list"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "volume"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "idle"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:7586): DEBUG: Adding property: CanSeek
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:7586): DEBUG: Adding property: CanSeek
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "speed"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "volume"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "playlist-count"
** (gnome-mpv:7586): DEBUG: Main window has been shadowed; sending global keyup to mpv
** (gnome-mpv:7586): DEBUG: Main window has been shadowed; sending global keyup to mpv
** INFO: Loading file (append=FALSE, update=TRUE): /home/maxim/Videos/trailer_1080p.ogg
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "idle"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:7586): DEBUG: Adding property: CanSeek
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "playlist-pos"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "playlist-count"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "media-title"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "playlist-pos"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "idle"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:7586): DEBUG: Adding property: CanSeek
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "playlist-pos"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "playlist-count"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "metadata"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: Metadata
** INFO: Failed to retrieve property "time-pos" using mpv format 5. Reason: property unavailable.
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "aid"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "chapters"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "length"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "track-list"
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "metadata"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: Metadata
** (gnome-mpv:7586): DEBUG: Retrieved video size: 1920x1080
** (gnome-mpv:7586): DEBUG: Retrieved option --window-scale=1.000000
** (gnome-mpv:7586): DEBUG: Retrieved option --autofit-larger=75%x0
** (gnome-mpv:7586): DEBUG: Target video area size: 960x768
** (gnome-mpv:7586): DEBUG: Set video size multiplier to 0.500000
** (gnome-mpv:7586): DEBUG: Resizing window to 960x540
** (gnome-mpv:7586): DEBUG: Retrieved video size: 1920x1080
** (gnome-mpv:7586): DEBUG: Retrieved option --window-scale=1.000000
** (gnome-mpv:7586): DEBUG: Retrieved option --autofit-larger=75%x0
** (gnome-mpv:7586): DEBUG: Target video area size: 960x768
** (gnome-mpv:7586): DEBUG: Set video size multiplier to 0.500000
** (gnome-mpv:7586): DEBUG: Resizing window to 960x540
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:7586): DEBUG: Adding property: CanSeek
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:7586): DEBUG: Adding property: CanSeek
** (gnome-mpv:7586): DEBUG: Received mpv property change event for "core-idle"
** (gnome-mpv:7586): DEBUG: Emitting property change event on interface org.mpris.MediaPlayer2.Player
** (gnome-mpv:7586): DEBUG: Adding property: PlaybackStatus
** (gnome-mpv:7586): DEBUG: Adding property: CanSeek
Segmentation fault (core dumped)
[maxim@localhost ~]$ 
```

**Comment by gnome-mpv** [comment]
Does 91f654685d8ed81936e2ff3cc17b71909489cc4b fix the crash?

**Comment by region51** [comment]
>Does 91f6546 fix the crash?

@gnome-mpv yes :+1:
