### ISSUE TITLE
Crash when closing window

### ISSUE THREAD

**Issue by TingPing** [gnome-mpv/gnome-mpv#351]
1. Open a second window in an existing instance
2. Ctrl+q
3. Get crash or try again

So the cause of this is straightforward but there are a few ways to solve it:

The `"win.close"` action leads to `gmpv_view_quit()` which calls `gtk_window_close(GTK_WINDOW(view->wnd));`.

This is bad since the view keeps using the dangling window pointer all over and also the controller that owns the view keeps using the view.

Personally I think this current design is poorly laid out and would have the View own everything because it is what is destroyed and everything should go with it. You can ofc just redesign it for quit to destroy the controller though I hit a few issues with that or you can just make the controller use `g_object_weak_ref()` or such and just react to the window disappearing from under it. I'll leave that decision to you I suppose.

**Comment by gnome-mpv** [comment]
I can't seem reproduce this. I tried opening/closing a second window about 10 times but that doesn't make it crash.

>The "win.close" action leads to gmpv_view_quit() which calls gtk_window_close(GTK_WINDOW(view->wnd));.
>This is bad since the view keeps using the dangling window pointer all over and also the controller that owns the view keeps using the view.

I'm not sure this is the problem. The view handles `delete-event` from the window and emits its own signal which gets re-emitted by the controller to `GmpvApplication`. The handler in `GmpvApplication` will then call `g_object_unref()` to destroy the controller; the controller has no chance to use the view.

**Comment by TingPing** [comment]
I can always reproduce, here is a typical traceback:

```gdb
#0  gtk_widget_get_scale_factor (widget=<optimized out>)
    at /home/tingping/jhbuild/checkout/gtk+-3/gtk/gtkwidget.c:10906
        display = <optimized out>
        monitor = <optimized out>
        __func__ = "gtk_widget_get_scale_factor"
#1  0x00007ffff766a619 in gtk_css_widget_node_get_style_provider (node=0x555555d93700)
    at /home/tingping/jhbuild/checkout/gtk+-3/gtk/gtkcsswidgetnode.c:246
        widget_node = 0x555555d93700
        context = <optimized out>
        node = 0x555555d93700
        widget_node = 0x555555d93700
        context = <optimized out>
#2  0x00007ffff7650418 in gtk_css_node_get_style_provider_or_null (cssnode=0x555555d93700)
    at /home/tingping/jhbuild/checkout/gtk+-3/gtk/gtkcssnode.c:121
No locals.
#3  gtk_css_node_invalidate_style_provider (cssnode=<optimized out>)
    at /home/tingping/jhbuild/checkout/gtk+-3/gtk/gtkcssnode.c:1320
        child = 0x555555d93700
#4  0x00007ffff646a69d in g_closure_invoke (closure=0x555555cce980, return_value=0x0, 
    n_param_values=1, param_values=0x7fffffffcaa0, invocation_hint=0x7fffffffca40)
    at /home/tingping/jhbuild/checkout/glib/gobject/gclosure.c:804
        marshal = 0x7ffff646c4c0 <g_cclosure_marshal_VOID__VOID>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x555555cce960
        __func__ = "g_closure_invoke"
#5  0x00007ffff647d6ce in signal_emit_unlocked_R (node=node@entry=0x55555587f080, 
    y=0, instance=instance@entry=0x5555558760a0, 
    emission_return=emission_return@entry=0x0, 
    instance_and_params=instance_and_params@entry=0x7fffffffcaa0)
    at /home/tingping/jhbuild/checkout/glib/gobject/gsignal.c:3635
        tmp = <optimized out>
        handler = 0x555555d94a80
        accumulator = 0x0
        emission = {next = 0x7fffffffd7c0, instance = 0x5555558760a0, ihint = {signal_id = 180, 
            detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 4}
        handler_list = 0x555555d94880
        return_accu = 0x0
        accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, 
              v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, 
              v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, 
              v_pointer = 0x0}}}
        signal_id = 180
        max_sequential_handler_number = 8104
        return_value_altered = 1
#6  0x00007ffff6485f45 in g_signal_emit_valist (instance=<optimized out>, 
    signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffcc48)
    at /home/tingping/jhbuild/checkout/glib/gobject/gsignal.c:3391
        instance_and_params = 0x7fffffffcaa0
        signal_return_type = <optimized out>
        param_values = 0x7fffffffcab8
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#7  0x00007ffff6486812 in g_signal_emit (instance=instance@entry=0x5555558760a0, 
    signal_id=<optimized out>, detail=detail@entry=0)
    at /home/tingping/jhbuild/checkout/glib/gobject/gsignal.c:3447
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffffffcd20, 
            reg_save_area = 0x7fffffffcc60}}
```

Somewhere, something is holding an invalid pointer to the widget after its destruction and using it.

**Comment by gnome-mpv** [comment]
Can you check if this [patch](https://github.com/gnome-mpv/gnome-mpv/files/1870059/remove-gsource.txt) fixes the problem?

**Comment by TingPing** [comment]
No change.

**Comment by gnome-mpv** [comment]
@TingPing: Can you check if this is still reproducible?

**Comment by TingPing** [comment]
No longer crashes here.
