### ISSUE TITLE
GTK_IS_WIDGET (widget) failed spams journalctl

### ISSUE THREAD

**Issue by ryanmusante** [gnome-mpv/gnome-mpv#355]
Overview Description:
gnome-mpv[26629]: gtk_widget_is_visible: assertion 'GTK_IS_WIDGET (widget)' failed

Steps to Reproduce:
1. Run gnome mpv
2. monitor journalctl

gnome-mpv --version                                                                                         
GNOME MPV 0.14

Additional Information:

**Comment by ryanmusante** [comment]
Distro: Manjaro x86_64
WM: Muffin
DE: Cinnamom 3.8.1

**Comment by gnome-mpv** [comment]
I'm still unable to reproduce this using a fresh installation of Manjaro with Cinnamon/Muffin.

Can you try running `gdb -ex 'set pagination off' -ex run -ex bt --args gnome-mpv --g-fatal-warnings` and post the output here?

**Comment by ryanmusante** [comment]
```
>>> gdb -ex 'set pagination off' -ex run -ex bt --args gnome-mpv --g-fatal-warnings                    
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gnome-mpv...(no debugging symbols found)...done.
Starting program: /usr/bin/gnome-mpv --g-fatal-warnings
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffce088700 (LWP 29987)]
[New Thread 0x7fffcd887700 (LWP 29988)]
[New Thread 0x7fffcca0f700 (LWP 29989)]
[New Thread 0x7fffbf960700 (LWP 29990)]
[New Thread 0x7fffbf15f700 (LWP 29992)]
[New Thread 0x7fffbe95e700 (LWP 29993)]
[New Thread 0x7fffbe15d700 (LWP 29994)]

(gnome-mpv:29889): Gtk-CRITICAL **: 22:11:38.686: gtk_widget_is_visible: assertion 'GTK_IS_WIDGET (widget)' failed

Thread 1 "gnome-mpv" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff5de7ed2 in ?? () from /usr/lib/libglib-2.0.so.0
#0  0x00007ffff5de7ed2 in  () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff5de923d in g_logv () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff5de93a0 in g_log () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff74925bb in gtk_widget_is_visible () at /usr/lib/libgtk-3.so.0
#4  0x0000555555577f33 in  ()
#5  0x00007ffff5de2cb3 in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff5de21d6 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff5de25b1 in  () at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff5de263e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff63a397e in g_application_run () at /usr/lib/libgio-2.0.so.0
#10 0x00005555555608e3 in main ()
(gdb) 

```

**Comment by ryanmusante** [comment]
I found that libgtk-3.so.0 is owned by gtk3-classic for my system. I remember a longtime back that I had replaced it to deal with CSD client side decorations.
```
~ >>> sudo pacman -Qo /usr/lib/libgtk-3.so.0                                                                        
[sudo] password for ryan:
/usr/lib/libgtk-3.so.0 is owned by gtk3-classic 3.22.30-0.1
```
I replaced with original gtk3 and it seems problem is gone. I wonder how many other people are unaware of this incompatibility with gtk3-classic and how many other applications are affected by it. I apologize for not doing due diligence or else I would have found that sooner.
```
~ >>> sudo pacman -S gtk3                                                                                           
resolving dependencies...
looking for conflicting packages...
:: gtk3 and gtk3-classic are in conflict (gtk3-print-backends). Remove gtk3-classic? [y/N] y
```
Confirmed  no fatal warnings:
```
Starting program: /usr/bin/gnome-mpv --g-fatal-warnings
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffcddd3700 (LWP 23940)]
[New Thread 0x7fffcd5d2700 (LWP 23941)]
[New Thread 0x7fffc7fff700 (LWP 23942)]
[New Thread 0x7fffc75c3700 (LWP 23943)]
[New Thread 0x7fffc6bbc700 (LWP 23944)]
[New Thread 0x7fffc63bb700 (LWP 23945)]
[New Thread 0x7fffc5bba700 (LWP 23946)]
[New Thread 0x7fffc53b9700 (LWP 23947)]
[Thread 0x7fffc6bbc700 (LWP 23944) exited]
[Thread 0x7fffc63bb700 (LWP 23945) exited]
[Thread 0x7fffc53b9700 (LWP 23947) exited]
[Thread 0x7fffc5bba700 (LWP 23946) exited]
[Thread 0x7fffc75c3700 (LWP 23943) exited]
[New Thread 0x7fffc75c3700 (LWP 24047)]
[Thread 0x7fffc7fff700 (LWP 23942) exited]
[Thread 0x7fffcd5d2700 (LWP 23941) exited]
[Thread 0x7fffcddd3700 (LWP 23940) exited]
[Thread 0x7ffff7f4b180 (LWP 23932) exited]
[Inferior 1 (process 23932) exited normally]
```

**Comment by gnome-mpv** [comment]
>I replaced with original gtk3 and it seems problem is gone. I wonder how many other people are unaware of this incompatibility with gtk3-classic and how many other applications are affected by it. I apologize for not doing due diligence or else I would have found that sooner.

No problem, and thanks for letting us know!

**Comment by TomaszGasior** [comment]
I'm author of gtk3-mushrooms (gtk3-classic). Problem was caused by small popovers dirty hack. It's fixed now. I'm sorry for unwanted noise!

**Comment by ryanmusante** [comment]
Very nice, thank you!
